EnableEventWaiting
DisableEventWaiting
SwapScreenBuffer
PollInputEvents
BeginMode2D
EndMode2D
BeginMode3D
EndMode3D
BeginVrStereoMode
EndVrStereoMode
LoadVrStereoConfig
UnloadVrStereoConfig
GetMouseRay
GetCameraMatrix
GetCameraMatrix2D
GetWorldToScreen
GetWorldToScreenEx
GetWorldToScreen2D
GetScreenToWorld2D
SetTargetFPS
GetRandomValue
SetRandomSeed
TakeScreenshot
OpenURL
CompressData
DecompressData
EncodeDataBase64
DecodeDataBase64
SetCameraMode
UpdateCamera
SetCameraPanControl
SetCameraAltControl
SetCameraSmoothZoomControl
SetCameraMoveControls
DrawPixel
DrawPixelV
DrawLineBezier
DrawLineBezierQuad
DrawLineBezierCubic
DrawLineBezierStrip
DrawCircle
DrawCircleSector
DrawCircleSectorLines
DrawCircleGradient
DrawCircleV
DrawCircleLines
DrawEllipse
DrawEllipseLines
DrawRing
DrawRingLines
DrawRectangleGradientV
DrawRectangleGradientH
DrawRectangleGradientEx
DrawRectangleLines
DrawRectangleLinesEx
DrawRectangleRounded
DrawRectangleRoundedLines
DrawTriangleLines
DrawTriangleFan
DrawTriangleStrip
DrawPolyLines
DrawPolyLinesEx
CheckCollisionCircles
CheckCollisionCircleRec
CheckCollisionPointCircle
CheckCollisionPointTriangle
CheckCollisionPointPoly
CheckCollisionLines
CheckCollisionPointLine
GetCollisionRec
SaveStorageValue
LoadStorageValue
GenImageText
GenImageGradientV
GenImageGradientH
GenImageGradientRadial
GenImageChecked
GenImageWhitenoise
GenImageCellular
GenImageAlphaBorder
ImageDrawRectangleLines
ImageDrawCircleLines
ImageDrawCircleLinesV
DrawTextureQuad
DrawTextureTiled
DrawTextureNPatch
DrawTexturePoly
ColorNormalize
ColorFromNormalized
ColorAlpha
GetColor
DrawFPS
CodepointToUTF8
TextCodepointsToUTF8
TextToUtf8
CodepointToUtf8
TextCopy
TextIsEqual
TextLength
TextSubtext
TextInsert
TextJoin
TextSplit
TextAppend
TextFindIndex
TextToUpper
TextToLower
TextToPascal
TextToInteger
GetCodepointNext
GetCodepointPrevious
LoadUTF8
UnloadUTF8
DrawLine3D
DrawPoint3D
DrawCircle3D
DrawTriangle3D
DrawTriangleStrip3D
DrawCube
DrawCubeV
DrawCubeWires
DrawCubeWiresV
DrawCubeTexture
DrawCubeTextureRec
DrawCubeTexturesRec
DrawSphere
DrawSphereEx
DrawSphereWires
DrawCylinder
DrawCylinderEx
DrawCylinderWires
DrawCylinderWiresEx
DrawPlane
DrawRay
DrawGrid
LoadModel
LoadModelFromMesh
UnloadModel
UnloadModelKeepMeshes
GetModelBoundingBox
DrawModel
DrawModelEx
DrawModelWires
DrawModelWiresEx
DrawBoundingBox
DrawBillboard
DrawBillboardRec
DrawBillboardPro
UploadMesh
UpdateMeshBuffer
UnloadMesh
DrawMesh
DrawMeshInstanced
ExportMesh
GetMeshBoundingBox
GenMeshTangents
GenMeshPoly
GenMeshPlane
GenMeshCube
GenMeshSphere
GenMeshCylinder
GenMeshCone
GenMeshTorus
GenMeshKnot
GenMeshHeightmap
GenMeshCubicmap
LoadMaterials
LoadMaterialsDefault
UnloadMaterial
SetMaterialTexture
SetModelMeshMaterial
LoadModelAnimations
UpdateModelAnimation
UnloadModelAnimation
UnloadModelAnimations
IsModelAnimationValid
CheckCollisionSpheres
CheckCollisionBoxes
CheckCollisionBoxSphere
GetRayCollisionSphere
GetRayCollisionBox
GetRayCollisionMesh
GetRayCollisionTriangle
GetRayCollisionQuad
GenImageWhiteNoise
GenImagePerlinNoise
LoadMaterialDefault
GenMeshHemiSphere
GenMeshBinormals
GetRayCollisionModel
DrawCapsule
DrawCapsuleWires
